### ISSUE TITLE
Update About Us page

### ISSUE THREAD

**Issue by jonathanwj** [CS2103JAN2018-F09-B4/main#38]
**TODO**
- [x] Replace info of SE-EDU developers with info of your team

- [x] Including the name/photo
- [x] The photo of a team member should be ```doc/images/githbub_username_in_lower_case.pnge.g. docs/images/damithc.png```
- [x] Indicate the different roles played and responsibilities held by each team member. **( Refer to cs2103 [admin page](https://nus-cs2103-ay1718s2.github.io/website/admin/index.html#admin-project-v11) for roles and responsibility)**
