### ISSUE TITLE
Update README.adoc page

### ISSUE THREAD

**Issue by jonathanwj** [CS2103JAN2018-F09-B4/main#39]
**TODO**

- [x] Add a UI mockup of your intended final product. Image of the UI should be ```docs/images/Ui.png```

- [x] Restructure this page to look like the home page of a real product
- [x] Remove Learning Outcomes link and related pages.
- [x] Acknowledge the original source of the code

[admin page v1.1](https://nus-cs2103-ay1718s2.github.io/website/admin/index.html#admin-project-v11)
